In [1]:
import numpy as np

# 1.Create ndarray:-

In [3]:
a=np.array(54)
print(a,type(a),a.ndim)
#O/p- 54 <class 'numpy.ndarray'> 0

b=np.array([1,2,3])
print(b,type(b),b.ndim)

c=np.array([[1,2,3],[4,5,6]])
print(c,type(c),c.ndim)

#O/p-
#[[1 2 3]
 #[4 5 6]] <class 'numpy.ndarray'> 2

d=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[7,8,9]]])
print(d,type(d),d.ndim)

54 <class 'numpy.ndarray'> 0
[1 2 3] <class 'numpy.ndarray'> 1
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> 2
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [7 8 9]]] <class 'numpy.ndarray'> 3


# 2.Function by which we can convert datatype:-

## asarray() -- asarray(input,dtype,order)
#### input=list or tuple or any combination
#### dtype= our required datatype like int,float,S1 (string byte)
#### order=Row major-'C' or'c' (default)
#### order=Column major-'F' or 'f'


In [4]:
import numpy as np

In [6]:
l=[[10,20,30],[40,50,60]]

In [15]:
a=np.asarray(l,dtype='int',order='f')
print(a)

[[10 20 30]
 [40 50 60]]


In [16]:
for i in np.nditer(a):
    print(i)

10
40
20
50
30
60


## frombuffer() -- frombuffer(buffer,dtype,count,offset)
### buffert=list or tuple or any combinatio
### 
dtype= our required datatype like int,float,S1 (string byt
### count=-1()default value ----can resist the data length
offset=0 (default value) ---from which position we need to start'f'¶

In [23]:
my_list = [1, 2, 3, 4, 5]

# Convert list to bytes
byte_data = bytes(my_list)
print(byte_data)

b'\x01\x02\x03\x04\x05'


In [27]:
s=b'pri ya'
a=np.frombuffer(s,dtype='S1',count=3,offset=3)
print(a)

[b' ' b'y' b'a']


## fromiter()--- fromiter(iterable,dtype,count)

In [29]:
import numpy as np

In [34]:
t=(10,20,30)
a=np.fromiter(t,dtype='float',count=2)
print(a)

[10. 20.]


# 3.Create an array with numerical range:-
### arange()---arange(startindex, stop index, step size, dtype)

In [38]:
import numpy as np
print(np.arange(0,10,2,dtype='int'))

[0 2 4 6 8]


In [52]:
np.arange(0,10,2,dtype='float')

array([0., 2., 4., 6., 8.])

In [53]:
a=np.arange(0,10,2,dtype='float')
print(a)

[0. 2. 4. 6. 8.]


## linespace()---linsespace(start index, stop index,number,endpoint,retstep,dtype)

In [46]:
print(np.linspace(0,10,4,endpoint=False,retstep=False,dtype='int'))

[0 2 5 7]


In [50]:
print(np.linspace(0,10,4,endpoint=False,retstep=True,dtype='int'))

(array([0, 2, 5, 7]), 2.5)


In [54]:
a=np.linspace(0,10,4,endpoint=False,retstep=True,dtype='float')
print(a)

(array([0. , 2.5, 5. , 7.5]), 2.5)


In [55]:
b=np.linspace(0,10,endpoint=False,retstep=True,dtype='int')
print(b)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8,
       8, 9, 9, 9, 9, 9]), 0.2)


In [56]:
l=[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8,
       8, 9, 9, 9, 9, 9]
print(len(l))

50


In [57]:
print(np.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


## logspace()--- logspace(start index, stop index,number,endpoint,base,dtype)
base=base of log value (default=10)

In [66]:
a=np.logspace(0,10,4,endpoint=False,base=2,dtype='int')
print(a)

[  1   5  32 181]


# 4.Initialising array in NumPy:-

In [71]:
a=[[1,2,3,4],[3,4,5,6]]
print(np.shape(a))

(2, 4)


In [77]:
b=[[1,2,4],[3,5,6]]
print(np.shape(b))

(2, 3)


In [78]:
print(np.reshape(b,(3,2)))

[[1 2]
 [4 3]
 [5 6]]


In [81]:
#print(np.reshape(b,(3,3)))   ---- raise an error

In [84]:
print(np.zeros((2,3),dtype='int'))

[[0 0 0]
 [0 0 0]]


In [85]:
print(np.ones((2,3),dtype='int'))

[[1 1 1]
 [1 1 1]]


In [86]:
print(np.full((2,3),20))

[[20 20 20]
 [20 20 20]]


In [94]:
print(np.eye((4),dtype='int'))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# 5.Accessing the elements of ndarray:-

In [98]:
# 1-D array
a=np.array([1,2,3])
print(a)
print('****')
print(a[-1])

[1 2 3]
****
3


In [102]:
# 2-D array
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b[0,1])

[[1 2 3]
 [4 5 6]]
2


In [108]:
# 3-D array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c[1,0,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
8


# 6.Slicing operation on ndarray:-

In [116]:
#1-D array
a=np.array([1,2,3,4,5])
print(a[1::2])

[2 4]


In [121]:
#2-D array
b=np.array([[1,2,3],[4,5,6]])
print(b[1,:2:])

[4 5]


In [127]:
# 3-D array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print('****')
print(c[0,0,::])
print(c[1,0,-1::-1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
****
[1 2 3]
[9 8 7]


# 7.Axis:-

In [134]:
a=np.array([[7,2,6],[3,5,1]])
print(a)
print('*****')
print(np.sort(a,axis=0))
print('*****')
print(np.sort(a,axis=1))

[[7 2 6]
 [3 5 1]]
*****
[[3 2 1]
 [7 5 6]]
*****
[[2 6 7]
 [1 3 5]]


# 8.Datatypes used in array:-

In [138]:
a=np.array([1,2,3])
print(a.dtype)

int32


In [140]:
b=np.array([1,2,3],dtype='U')
print(b)

['1' '2' '3']


In [142]:
print(b)
x=b.astype('f')
print(x)

['1' '2' '3']
[1. 2. 3.]


In [148]:
c=['a',2,3]
print(c)

['a', 2, 3]


In [158]:
d=np.array([1,0,22,-1,45])
print(d.astype('bool'))

[ True False  True  True  True]


In [152]:
# copy()-------------

a=np.array([1,2,3])
c=a.copy()
print(a,'*',c)

[1 2 3] * [1 2 3]


In [153]:
c[1]=8
print(c,'*',a)

[1 8 3] * [1 2 3]


In [155]:
b=np.array([5,6,7])
v=b.view()
print(v)

[5 6 7]


In [157]:
v[1]=100
print(v,'*',b)

[  5 100   7] * [  5 100   7]


# 9.Joining Arrays:-

In [159]:
a=np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [160]:
b=np.arange(7,13).reshape(2,3)
print(b)

[[ 7  8  9]
 [10 11 12]]


In [163]:
print(np.concatenate((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [164]:
print(np.concatenate((a,b),axis=1))

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [165]:
print(np.stack((a,b)))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]


In [166]:
print(np.vstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [167]:
print(np.hstack((a,b)))

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [168]:
print(np.dstack((a,b)))

[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


# 10.Splitting Array:-

In [2]:
import numpy as np

In [3]:
a=np.arange(6)
print(a) 

[0 1 2 3 4 5]


In [170]:
print(np.split(a,2))

[array([0, 1, 2]), array([3, 4, 5])]


In [176]:
#print(np.split(a,4))-------------- #ValueError

In [175]:
print(np.array_split(a,4))

[array([0, 1]), array([2, 3]), array([4]), array([5])]


In [4]:
print(np.hsplit(a,2))

[array([0, 1, 2]), array([3, 4, 5])]


In [7]:
#print(np.vsplit(a,2))   ----   vsplit only works on arrays of 2 or more dimensions


In [13]:
x=np.array([[7,2,6],[3,5,1]])
#print(np.hsplit(x,2))      ------- ValueError
print(np.vsplit(x,2))

[array([[7, 2, 6]]), array([[3, 5, 1]])]


# 11.Searching:-

In [2]:
import numpy as np
a=np.arange(10,100,10)
print(a)

[10 20 30 40 50 60 70 80 90]


In [3]:
print(np.where(a==30))
print(np.where(a%30==0))

(array([2], dtype=int64),)
(array([2, 5, 8], dtype=int64),)


In [4]:
b=[10,20,30,40]
print(np.searchsorted(a,25))

2


In [7]:
c=[10,20,30,40,50]
print(np.searchsorted(a,[25,35,45]))    #it will search individually

[2 3 4]


## 12. Sort():-

In [14]:
a=np.array([20,30,40,10,50])
print(np.sort(a))

[10 20 30 40 50]


In [24]:
b=np.array([[20,10,50],[60,80,40]])
print(np.sort(b))   

[[10 20 50]
 [40 60 80]]


In [25]:
b=np.array([[20,10,50],[60,80,40]])
print(np.sort(b,axis=0))

[[20 10 40]
 [60 80 50]]


In [36]:
c=np.dtype([('name','S10'),('Perc',float)])
students=np.array([('abc',78.45),('xyz',90.33),('pqr',45.67)],dtype=c)
print(np.sort(students,order='Perc'))

[(b'pqr', 45.67) (b'abc', 78.45) (b'xyz', 90.33)]


In [37]:
c=np.dtype([('name','S10'),('Perc',float)])
students=np.array([('abc',78.45),('xyz',90.33),('pqr',45.67)],dtype=c)
print(np.sort(students,order='name'))

[(b'abc', 78.45) (b'pqr', 45.67) (b'xyz', 90.33)]


In [5]:
import numpy as np
c=np.dtype([('name','S10'),('Perc',float)])
students=np.array([('abc',78.45),('xyz',90.33),('pqr',45.67)],dtype=c)
print(np.sort(students,king='merge',order='Perc'))

TypeError: sort() got an unexpected keyword argument 'king'

## 13.Arithmetic Operation:-

In [7]:
import numpy as np
a=np.array([[1,2,3,],[4,5,6],[7,8,9]])
b=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
print(np.shape(a))
print(np.shape(b))

(3, 3)
(3, 3)


In [9]:
print(np.add(a,b))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [10]:
print(np.subtract(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
c=np.array([4,5,6])
print(c,np.shape(c))

[4 5 6] (3,)


In [12]:
print(np.add(a,c))

[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [16]:
d=np.array([10,11])
print(d,np.shape(d))
#print(np.add(a,d)) -------ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

[10 11] (2,)


In [17]:
e=np.array([[10,11],[2,3],[7,5]])
print(np.shape(e))

(3, 2)


In [21]:
f=np.array([10])
print(f,np.shape(f))
print(np.add(a,f))

[10] (1,)
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [22]:
print(np.divide(a,b))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [23]:
print(np.mod(a,10))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(np.reciprocal(a))

[[1 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
f=np.array([0.5,0.4,0.3])
print(np.reciprocal(f))

[2.         2.5        3.33333333]


In [30]:
complex=np.array([2+3j,4-1j,7+9j])
print(np.real(complex))
print(np.imag(complex))
print(np.conjugate(complex))

[2. 4. 7.]
[ 3. -1.  9.]
[2.-3.j 4.+1.j 7.-9.j]


## 14.Statistically Functios:-

In [31]:
import numpy as np

In [37]:
a=np.array([[4,3,8],[9,6,2]])
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

2
[4 3 2]
[3 2]


In [39]:
print(np.max(a))
print(np.average(a))

9
5.333333333333333


In [44]:
w=[1,2,3]
print(np.average(a,weights=w,axis=1))

[5.66666667 4.5       ]
